"""PDF report generator for BookFinder.

Converts Markdown summaries into polished, professional PDF documents
using fpdf2 (pure Python, no system dependencies).
"""

import os
import re

from fpdf import FPDF


class ResearchPDF(FPDF):
    """Custom PDF class for research summaries."""

    def __init__(self, title: str = "", author: str = "", **kwargs):
        super().__init__(**kwargs)
        self.doc_title = title
        self.doc_author = author
        self.set_auto_page_break(auto=True, margin=25)
        self.set_margins(25, 25, 25)

    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(150, 150, 150)
            self.cell(0, 10, self.doc_title, align="L")
            self.ln(5)
            self.set_draw_color(200, 200, 200)
            self.line(25, self.get_y(), self.w - 25, self.get_y())
            self.ln(5)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

    def cover_page(self, title: str, author: str = "", year: str = "",
                   summary_type: str = "Research Summary"):
        """Add a styled cover page."""
        self.add_page()
        self.ln(60)

        # Summary type label
        self.set_font("Helvetica", "", 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, summary_type.upper(), align="C")
        self.ln(15)

        # Title
        self.set_font("Helvetica", "B", 24)
        self.set_text_color(30, 30, 60)
        self.multi_cell(0, 12, title, align="C")
        self.ln(10)

        # Divider
        self.set_draw_color(0, 180, 220)
        self.set_line_width(1)
        center_x = self.w / 2
        self.line(center_x - 40, self.get_y(), center_x + 40, self.get_y())
        self.ln(15)

        # Author / Year
        if author:
            self.set_font("Helvetica", "", 14)
            self.set_text_color(80, 80, 80)
            self.cell(0, 8, author, align="C")
            self.ln(8)
        if year:
            self.set_font("Helvetica", "", 12)
            self.set_text_color(120, 120, 120)
            self.cell(0, 8, year, align="C")
            self.ln(8)

        # Footer note
        self.set_y(-40)
        self.set_font("Helvetica", "I", 9)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "Generated by BookFinder", align="C")


def markdown_to_pdf(
    markdown_text: str,
    output_path: str,
    title: str = "Research Summary",
    author: str = "",
    year: str = "",
    summary_type: str = "Research Summary",
) -> str:
    """
    Convert a Markdown summary to a polished PDF.

    Supports:
    - # H1, ## H2, ### H3 headings
    - **bold** and *italic* text
    - Bullet lists (- or *)
    - Numbered lists
    - Blockquotes (>)
    - Horizontal rules (---)
    - Regular paragraphs

    Args:
        markdown_text: The Markdown content.
        output_path: Where to save the PDF.
        title: Document title (cover page and headers).
        author: Author name (cover page).
        year: Year (cover page).
        summary_type: Label for the cover page (e.g. "Research Summary", "Book Summary").

    Returns:
        Path to the generated PDF.
    """
    pdf = ResearchPDF(title=title, author=author)
    pdf.alias_nb_pages()

    # Cover page
    pdf.cover_page(title, author, year, summary_type)

    # Content pages
    pdf.add_page()

    lines = markdown_text.split("\n")
    i = 0

    while i < len(lines):
        line = lines[i]

        # Skip empty lines
        if not line.strip():
            pdf.ln(4)
            i += 1
            continue

        # Horizontal rule
        if re.match(r"^-{3,}$|^\*{3,}$|^_{3,}$", line.strip()):
            pdf.ln(4)
            pdf.set_draw_color(200, 200, 200)
            pdf.line(25, pdf.get_y(), pdf.w - 25, pdf.get_y())
            pdf.ln(8)
            i += 1
            continue

        # Headings
        heading_match = re.match(r"^(#{1,3})\s+(.+)", line)
        if heading_match:
            level = len(heading_match.group(1))
            text = heading_match.group(2).strip()
            text = _strip_md_formatting(text)

            if level == 1:
                pdf.ln(8)
                pdf.set_font("Helvetica", "B", 18)
                pdf.set_text_color(30, 30, 60)
            elif level == 2:
                pdf.ln(6)
                pdf.set_font("Helvetica", "B", 14)
                pdf.set_text_color(40, 40, 80)
            else:
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 12)
                pdf.set_text_color(50, 50, 100)

            pdf.multi_cell(0, 7, text)
            pdf.ln(3)
            i += 1
            continue

        # Blockquote
        if line.strip().startswith(">"):
            quote_text = line.strip().lstrip("> ").strip()
            # Collect multi-line blockquotes
            while i + 1 < len(lines) and lines[i + 1].strip().startswith(">"):
                i += 1
                quote_text += " " + lines[i].strip().lstrip("> ").strip()

            quote_text = _strip_md_formatting(quote_text)
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(80, 80, 80)
            x = pdf.get_x()
            pdf.set_x(x + 10)
            # Draw quote bar
            y_before = pdf.get_y()
            pdf.multi_cell(pdf.w - 60, 6, quote_text)
            y_after = pdf.get_y()
            pdf.set_draw_color(0, 180, 220)
            pdf.set_line_width(0.8)
            pdf.line(33, y_before, 33, y_after)
            pdf.set_line_width(0.2)
            pdf.ln(4)
            i += 1
            continue

        # Bullet list
        if re.match(r"^\s*[-*]\s+", line):
            text = re.sub(r"^\s*[-*]\s+", "", line).strip()
            text = _strip_md_formatting(text)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            x = pdf.get_x()
            pdf.set_x(x + 8)
            pdf.cell(5, 6, "-")
            pdf.multi_cell(pdf.w - 63, 6, text)
            pdf.ln(1)
            i += 1
            continue

        # Numbered list
        num_match = re.match(r"^\s*(\d+)[.)]\s+(.+)", line)
        if num_match:
            num = num_match.group(1)
            text = _strip_md_formatting(num_match.group(2).strip())
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
            x = pdf.get_x()
            pdf.set_x(x + 8)
            pdf.cell(8, 6, f"{num}.")
            pdf.multi_cell(pdf.w - 66, 6, text)
            pdf.ln(1)
            i += 1
            continue

        # Regular paragraph — collect consecutive non-empty, non-special lines
        para_lines = [line.strip()]
        while i + 1 < len(lines):
            next_line = lines[i + 1]
            if (not next_line.strip() or
                next_line.strip().startswith("#") or
                next_line.strip().startswith(">") or
                re.match(r"^\s*[-*]\s+", next_line) or
                re.match(r"^\s*\d+[.)]\s+", next_line) or
                re.match(r"^-{3,}$|^\*{3,}$|^_{3,}$", next_line.strip())):
                break
            para_lines.append(next_line.strip())
            i += 1

        text = " ".join(para_lines)
        text = _strip_md_formatting(text)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 6, text)
        pdf.ln(3)
        i += 1

    pdf.output(output_path)
    return output_path


def _strip_md_formatting(text: str) -> str:
    """Remove Markdown inline formatting for plain-text PDF rendering."""
    # Bold
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"__(.+?)__", r"\1", text)
    # Italic
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    text = re.sub(r"_(.+?)_", r"\1", text)
    # Inline code
    text = re.sub(r"`(.+?)`", r"\1", text)
    # Links [text](url) -> text
    text = re.sub(r"\[(.+?)\]\(.+?\)", r"\1", text)
    # HTML comments
    text = re.sub(r"<!--.*?-->", "", text)
    # Sanitize Unicode characters that latin-1 can't encode
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text.strip()
