"""Summary generation and management for BookFinder.

Handles saving summaries (generated by Claude or other LLMs) and
converting them to polished PDFs. Includes stop-slop rules for
clean, human-readable prose.
"""

import json
import os

from .library import get_book, get_book_content, BookEntry
from .pdf_generator import markdown_to_pdf


# Stop-slop rules — embedded from https://github.com/hardikpandya/stop-slop
# These guide the LLM to write naturally without AI tells.
STOP_SLOP_RULES = """
Write clean, direct prose. Follow these rules strictly:

1. NO FILLER OPENINGS. Never start with "In today's...", "In the world of...",
   "When it comes to...", "It's worth noting that...", "Here's the thing...".
   Start with the actual point.

2. NO FORMULAIC STRUCTURES. Avoid the pattern of "X isn't just Y — it's Z."
   Avoid "Let's dive in", "Let's unpack", "Let's explore." Don't use
   "The reality is...", "The truth is...", "Here's why..."

3. USE ACTIVE VOICE. Say who does what. "The author argues..." not
   "It is argued that..."

4. BE SPECIFIC. Replace vague claims with concrete details. Use actual
   numbers, names, dates, and examples from the source material.

5. NO AI EMPHASIS CRUTCHES. Don't use "crucial", "vital", "essential",
   "game-changing", "revolutionary", "powerful", "robust", "comprehensive",
   "innovative", "cutting-edge", "fascinating", "remarkable". Use plain words.

6. NO META-COMMENTARY. Don't say "This summary covers...",
   "As we can see...", "It's important to note...", "In conclusion...".
   Just state the information.

7. NO DRAMATIC FRAGMENTATION. Don't use one-sentence paragraphs for
   dramatic effect. Don't end sections with rhetorical questions.

8. WRITE LIKE A KNOWLEDGEABLE PERSON explaining something to a peer.
   Not like a textbook, not like a blog post, not like a sales pitch.
"""

SUMMARY_PROMPT_TEMPLATE = """You are summarizing a research book for a game designer who needs
accurate, detailed information for their work. {focus_instruction}

{stop_slop_rules}

Book: "{title}" by {author} ({year})

Write a thorough summary covering:
- The book's main arguments and thesis
- Key facts, data, formulas, or technical details (be precise)
- Notable primary sources or evidence cited
- Historical context and significance
- Any maps, diagrams, or visual information described in text

Keep it factual and dense with information. Skip generic filler.
Length: aim for 1500-3000 words depending on the book's density.

---

BOOK CONTENT:

{content}
"""

TOPIC_SUMMARY_PROMPT = """You are synthesizing information from multiple research books
on a specific topic for a game designer. {focus_instruction}

{stop_slop_rules}

Topic: {topic}

Books being synthesized:
{book_list}

Write a unified research brief that:
- Synthesizes key findings across all sources
- Notes where sources agree or disagree
- Highlights the most useful facts, data, and details
- Provides specific references (author, page/section when possible)
- Organizes information thematically, not book-by-book

Length: aim for 2000-4000 words depending on the material.

---

BOOK CONTENTS:

{contents}
"""


def get_summary_prompt(
    book_id: str,
    focus: str = "",
) -> dict:
    """
    Generate the prompt for Claude to create a book summary.

    Returns a dict with 'system' and 'user' prompts that Claude
    should use to generate the summary. The stop-slop rules are
    embedded in the system prompt.

    Args:
        book_id: The book's library ID.
        focus: Optional focus area (e.g. "artillery formations",
               "economic factors"). Empty = general summary.

    Returns:
        Dict with 'prompt' (the full prompt text), 'title', 'author', 'year'.
    """
    book = get_book(book_id)
    if not book:
        return {"error": f"Book '{book_id}' not found in library."}

    content = get_book_content(book_id, translated=True, max_chars=100000)
    if not content:
        return {"error": "No extracted text available for this book."}

    focus_instruction = ""
    if focus:
        focus_instruction = f'Focus especially on: {focus}. Extract all relevant details about this topic.'

    prompt = SUMMARY_PROMPT_TEMPLATE.format(
        title=book.title,
        author=book.author or "Unknown",
        year=book.year or "Unknown",
        focus_instruction=focus_instruction,
        stop_slop_rules=STOP_SLOP_RULES,
        content=content,
    )

    return {
        "prompt": prompt,
        "title": book.title,
        "author": book.author,
        "year": book.year,
        "book_id": book_id,
    }


def get_topic_summary_prompt(
    book_ids: list[str],
    topic: str,
    focus: str = "",
) -> dict:
    """
    Generate a prompt for synthesizing multiple books on a topic.

    Args:
        book_ids: List of book IDs to synthesize.
        topic: The research topic.
        focus: Optional specific focus within the topic.

    Returns:
        Dict with 'prompt' text.
    """
    books = []
    contents = []

    for bid in book_ids:
        book = get_book(bid)
        if not book:
            continue

        content = get_book_content(bid, translated=True, max_chars=50000)
        if content:
            books.append(book)
            contents.append(f"### {book.title} by {book.author or 'Unknown'} ({book.year or '?'})\n\n{content}")

    if not books:
        return {"error": "No readable books found from the provided IDs."}

    book_list = "\n".join(
        f"- \"{b.title}\" by {b.author or 'Unknown'} ({b.year or '?'})"
        for b in books
    )

    focus_instruction = ""
    if focus:
        focus_instruction = f"Focus especially on: {focus}."

    prompt = TOPIC_SUMMARY_PROMPT.format(
        topic=topic,
        focus_instruction=focus_instruction,
        stop_slop_rules=STOP_SLOP_RULES,
        book_list=book_list,
        contents="\n\n---\n\n".join(contents),
    )

    return {
        "prompt": prompt,
        "topic": topic,
        "book_ids": book_ids,
        "book_count": len(books),
    }


def save_summary(
    book_id: str,
    summary_text: str,
    generate_pdf: bool = True,
    summary_type: str = "Book Summary",
) -> dict:
    """
    Save a summary to the book's library folder and optionally generate a PDF.

    Args:
        book_id: The book's library ID.
        summary_text: The Markdown summary text (generated by Claude).
        generate_pdf: Whether to also produce a PDF version.
        summary_type: Label for the PDF cover page.

    Returns:
        Dict with paths to saved files.
    """
    book = get_book(book_id)
    if not book:
        return {"error": f"Book '{book_id}' not found."}

    result = {"book_id": book_id, "title": book.title}

    # Save markdown summary
    summary_path = os.path.join(book.dir_path, "summary.md")
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary_text)
    result["summary_md"] = summary_path

    # Generate PDF
    if generate_pdf:
        pdf_path = os.path.join(book.dir_path, "summary.pdf")
        try:
            markdown_to_pdf(
                markdown_text=summary_text,
                output_path=pdf_path,
                title=book.title,
                author=book.author,
                year=book.year,
                summary_type=summary_type,
            )
            result["summary_pdf"] = pdf_path
        except Exception as e:
            result["pdf_error"] = str(e)

    # Update metadata
    metadata_path = book.metadata_path
    try:
        with open(metadata_path, "r", encoding="utf-8") as f:
            meta = json.load(f)
        meta["has_summary"] = True
        with open(metadata_path, "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2, ensure_ascii=False)
    except Exception:
        pass

    return result


def save_topic_summary(
    topic: str,
    book_ids: list[str],
    summary_text: str,
    generate_pdf: bool = True,
) -> dict:
    """
    Save a cross-book topic summary.

    Saves to the library root in a topic-specific folder.

    Args:
        topic: The research topic.
        book_ids: List of book IDs that were synthesized.
        summary_text: The summary text.
        generate_pdf: Whether to generate a PDF.

    Returns:
        Dict with paths to saved files.
    """
    from .library import _slugify, ensure_library

    ensure_library()
    from .config import LIBRARY_DIR

    topic_slug = _slugify(topic)
    topic_dir = os.path.join(LIBRARY_DIR, "_topics", topic_slug)
    os.makedirs(topic_dir, exist_ok=True)

    result = {"topic": topic, "book_ids": book_ids}

    # Save markdown
    summary_path = os.path.join(topic_dir, "summary.md")
    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary_text)
    result["summary_md"] = summary_path

    # Save metadata
    meta = {
        "topic": topic,
        "book_ids": book_ids,
        "type": "topic_summary",
    }
    with open(os.path.join(topic_dir, "metadata.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    # Generate PDF
    if generate_pdf:
        pdf_path = os.path.join(topic_dir, "summary.pdf")
        try:
            markdown_to_pdf(
                markdown_text=summary_text,
                output_path=pdf_path,
                title=topic,
                summary_type="Research Brief",
            )
            result["summary_pdf"] = pdf_path
        except Exception as e:
            result["pdf_error"] = str(e)

    return result
